export enum ZKType {
  NATIONALITY_IS_TUR = 'NATIONALITY_IS_TUR',
  NATIONALITY_IS_NOT_TUR = 'NATIONALITY_IS_NOT_TUR',
  AGE_IS_OVER_18 = 'AGE_IS_OVER_18',
  AGE_IS_OVER_24 = 'AGE_IS_OVER_24',
  AGE_IS_UNDER_18 = 'AGE_IS_UNDER_18',
  GENDER_IS_MAN = 'GENDER_IS_MAN',
  GENDER_IS_WOMAN = 'GENDER_IS_WOMAN',
  PASSPORT_ID_IS_VALID = 'PASSPORT_ID_IS_VALID',
  NATIONALITY_ID_IS_VALID = 'NATIONALITY_ID_IS_VALID',
}
