const props = [
  'backgroundColor',
  'borderWidth',
  'borderStyle',
  'borderColor',
  'flexDirection',
  'borderRadius',
  'minHeight',
  'alignItems',
  'justifyContent',
  'numberOfLines',
  'isPositionTop',
  'hasError',
  'editable',
  'isPlaceholderVisible',
  'hasRightIcon',
  'marginLeft',
  'hasSearch',
  'gridArea',
  'alignSelf',
  'hasSteps',
  'maxWidth',
  'marginBottom',
  'loading',
  'textAlign',
  'hasBottomMask',
  'minWidth',
  'zIndex',
  'isActive',
  'isFirstItem',
  'isLastItem',
  'labelProps',
  'descriptionProps',
  'borderTop',
  'uploading',
  'borderBottom',
  'sticky',
  'iconColor',
  'isHidden',
  'hasPressable',
  'isFullWidth',
  'box-sizing',
  'flexShrink',
  'activeOpacity',
  'hoverOpacity',
  'flexGrow',
  'underline',
  'pressedBackground',
];

function shouldForwardProp(propName: string) {
  return !props.includes(propName);
}

export default shouldForwardProp;
